# Generated by Django 3.2.3 on 2021-05-19 10:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_content_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
