# Generated by Django 3.2.3 on 2021-05-19 12:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_content_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
